name: 'Durazo & Associates, Inc.'
favicon: null
layout_spectrum: 0.15690248738974333
typography_spectrum: 0.08738685073330998
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5891409716568887
  lightness: 0.13448968320153654
  saturation: 0.4388830033130944
  rhythmicContrast: 0.5691448163706809
purpose: []
