title: Small business consulting and professional services.
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4388830033130944
  brandStrength: 0.5891409716568887
  lightness: 0.1344896832015365
  brandColors:
    - '#000000'
    - '#FDF6E6'
    - '#7C5A37'
    - '#E7C89A'
    - '#908474'
  rhythmicContrast: 0.5691448163706809
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: 'Durazo & Associates, Inc.'
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.9283154
layout_spectrum: 1
